---
- name: iperf3 Serverius Test
  hosts: all
 
  tasks:
 
  - name: iperf3 Serverius Test
   command: wget -4 -O /dev/null http://speedtest.serverius.net/files/2000mb.bin
   command: ~/iperf3 -c speedtest.serverius.net -p 5002 -P 10 -4
   
